export const FAKE_POPULAR_TV_SHOWS = [
  {
    adult: false,
    backdrop_path: "/dfX2UaHVE5c7kLBFbgmEZJuy4Ev.jpg",
    genre_ids: [10767, 35],
    id: 61818,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Late Night with Seth Meyers",
    overview:
      'Seth Meyers, who is "Saturday Night Live’s" longest serving anchor on the show’s wildly popular "Weekend Update," takes over as host of NBC’s "Late Night" — home to A-list celebrity guests, memorable comedy and the best in musical talent. As the Emmy Award-winning head writer for "SNL," Meyers has established a reputation for sharp wit and perfectly timed comedy, and has gained fame for his spot-on jokes and satire. Meyers takes his departure from "SNL" to his new post at "Late Night," as Jimmy Fallon moves to "The Tonight Show".',
    popularity: 5181.112,
    poster_path: "/gZlu4cTS1XS9FtZjC0hX7eRE0Sv.jpg",
    first_air_date: "2014-02-25",
    name: "Late Night with Seth Meyers",
    vote_average: 5.6,
    vote_count: 77,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 482.295,
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    vote_count: 13348,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/xl1wGwaPZInJo1JAnpKqnFozWBE.jpg",
    id: 59941,
    name: "The Tonight Show Starring Jimmy Fallon",
    original_language: "en",
    original_name: "The Tonight Show Starring Jimmy Fallon",
    overview:
      "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
    poster_path: "/xFOVcKxo7SSexJiLsTw2PrbNGcZ.jpg",
    media_type: "tv",
    genre_ids: [35, 10767],
    popularity: 4080.079,
    first_air_date: "2014-02-17",
    vote_average: 5.865,
    vote_count: 299,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/w0GA9tmKfRgxXj2zPUp0qzDuYjC.jpg",
    id: 60694,
    name: "Last Week Tonight with John Oliver",
    original_language: "en",
    original_name: "Last Week Tonight with John Oliver",
    overview:
      "A half-hour satirical look at the week in news, politics and current events.",
    poster_path: "/b12eM3FXNjN7yM7XYTIdmeQRud9.jpg",
    media_type: "tv",
    genre_ids: [10767, 35, 10763],
    popularity: 1092.421,
    first_air_date: "2014-04-27",
    vote_average: 7.9,
    vote_count: 627,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/amtOltTVcK9vQtL1iQS6p3LBi05.jpg",
    id: 62223,
    name: "The Late Late Show with James Corden",
    original_language: "en",
    original_name: "The Late Late Show with James Corden",
    overview:
      "Once Craig Ferguson retires, James Corden will be taking over The Late Late Show. The show is a late night talk show that interviews celebrities and has its own bits. And of course, it's all hosted by James Corden.",
    poster_path: "/qPmVoG8G9tc1nN8ZwGV2zYcknit.jpg",
    media_type: "tv",
    genre_ids: [10767],
    popularity: 2628.658,
    first_air_date: "2015-03-23",
    vote_average: 5.496,
    vote_count: 122,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/82qpvU7AzT9D8oC02fIceb5KAz8.jpg",
    id: 46648,
    name: "True Detective",
    original_language: "en",
    original_name: "True Detective",
    overview:
      "An American anthology police detective series utilizing multiple timelines in which investigations seem to unearth personal and professional secrets of those involved, both within or outside the law.",
    poster_path: "/cuV2O5ZyDLHSOWzg3nLVljp1ubw.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 570.299,
    first_air_date: "2014-01-12",
    vote_average: 8.306,
    vote_count: 3160,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/eLGICVIbVWke9U8SnUVrtXdwrlC.jpg",
    id: 79744,
    name: "The Rookie",
    original_language: "en",
    original_name: "The Rookie",
    overview:
      "Starting over isn’t easy, especially for small-town guy John Nolan who, after a life-altering incident, is pursuing his dream of being an LAPD officer. As the force’s oldest rookie, he’s met with skepticism from some higher-ups who see him as just a walking midlife crisis.",
    poster_path: "/wbeqBUFydztHDQ4h7dZqnknh5HE.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 35],
    popularity: 962.674,
    first_air_date: "2018-10-16",
    vote_average: 8.378,
    vote_count: 1715,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/l0XvAI856XdyDYEfr1njztjH7u0.jpg",
    id: 40075,
    name: "Gravity Falls",
    original_language: "en",
    original_name: "Gravity Falls",
    overview:
      "Twin brother and sister Dipper and Mabel Pines are in for an unexpected adventure when they spend the summer helping their great uncle Stan run a tourist trap in the mysterious town of Gravity Falls, Oregon.",
    poster_path: "/evxXr4OCH2YvhB8VchgDuArSyw0.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 9648, 10765, 10762],
    popularity: 248.893,
    first_air_date: "2012-06-15",
    vote_average: 8.6,
    vote_count: 2708,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/nfjqhuGFUWqJD14B4fxlSiZWfeR.jpg",
    id: 73107,
    name: "Barry",
    original_language: "en",
    original_name: "Barry",
    overview:
      "A listless hitman is enthralled by theatre acting and becomes eager to leave his old life behind in pursuit of a new career.",
    poster_path: "/j1XpwD11f0BAEI7pX6UdMhUVX2F.jpg",
    media_type: "tv",
    genre_ids: [35, 80, 18],
    popularity: 94.021,
    first_air_date: "2018-03-25",
    vote_average: 7.926,
    vote_count: 795,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/6AMu666ED8qPbep6iYtue11awvW.jpg",
    id: 71790,
    name: "S.W.A.T.",
    original_language: "en",
    original_name: "S.W.A.T.",
    overview:
      "A locally born and bred S.W.A.T. lieutenant is torn between loyalty to the streets and duty to his fellow officers when he's tasked to run a highly-trained unit that's the last stop for solving crimes in Los Angeles.",
    poster_path: "/1l7vsAIkqOzrqiPwjO27Cb5QdfJ.jpg",
    media_type: "tv",
    genre_ids: [80, 10759, 18],
    popularity: 1642.961,
    first_air_date: "2017-11-02",
    vote_average: 8.1,
    vote_count: 1289,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
    id: 63770,
    name: "The Late Show with Stephen Colbert",
    original_language: "en",
    original_name: "The Late Show with Stephen Colbert",
    overview:
      "Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater. Stephen Colbert, Chris Licht, Tom Purcell, and Jon Stewart are executive producers. Barry Julien and Denise Rehrig serve as co-executive producers.must watch",
    poster_path: "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
    media_type: "tv",
    genre_ids: [35, 10767],
    popularity: 6653.27,
    first_air_date: "2015-09-08",
    vote_average: 6.512,
    vote_count: 252,
    origin_country: ["US"],
  },
];
